# Generated by Django 5.0.1 on 2024-01-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_albumn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumn',
            name='created',
        ),
    ]
