# Generated by Django 5.0.1 on 2024-01-20 08:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_imagegallery_albumn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagegallery',
            new_name='Image',
        ),
    ]
