# Generated by Django 5.0.1 on 2024-01-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='profilepics'),
        ),
    ]
