# Generated by Django 5.0.1 on 2024-01-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0012_albumn_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vaultpin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
